import type { User, WatchlistItem, RecommendationCard, PerformanceRecord } from './types';

export const mockUser: User = {
  name: '지훈',
  timezone: 'Asia/Seoul',
  defaultRiskProfile: 'balanced',
  pushEnabled: true,
};

export const availableWatchlistItems: WatchlistItem[] = [
  { ticker: 'AAPL', name: 'Apple' },
  { ticker: 'TSLA', name: 'Tesla' },
  { ticker: 'NVDA', name: 'Nvidia' },
  { ticker: 'MSFT', name: 'Microsoft' },
  { ticker: 'AMZN', name: 'Amazon' },
  { ticker: 'META', name: 'Meta' },
  { ticker: 'TECH', name: 'Technology sector' },
  { ticker: 'HEALTH', name: 'Healthcare sector' },
  { ticker: 'CONSUMER', name: 'Consumer sector' },
];

export const defaultWatchlist: string[] = ['AAPL', 'TSLA', 'NVDA'];

// Balanced recommendations
const balancedRecommendations: RecommendationCard[] = [
  {
    id: 'nvda-balanced',
    ticker: 'NVDA',
    companyName: 'Nvidia',
    direction: 'BUY',
    entryRangeMin: 820,
    entryRangeMax: 835,
    targetRangeMin: 875,
    targetRangeMax: 895,
    stopPrice: 792,
    holdDays: 5,
    confidenceScore: 'balanced',
    actionLabel: '계획 매수',
    reasonLine: '데이터센터 수요와 최근 거래량 회복이 단기 추세 유지 가능성을 높입니다.',
  },
  {
    id: 'aapl-balanced',
    ticker: 'AAPL',
    companyName: 'Apple',
    direction: 'BUY',
    entryPrice: 168.40,
    targetPrice: 176.00,
    stopPrice: 162.80,
    holdDays: 4,
    confidenceScore: 'balanced',
    actionLabel: '분할 진입',
    reasonLine: '신제품 기대보다 자사주 매입과 방어적 수급이 단기 하방을 제한하고 있습니다.',
  },
  {
    id: 'tsla-balanced',
    ticker: 'TSLA',
    companyName: 'Tesla',
    direction: 'SELL',
    entryRangeMin: 151,
    entryRangeMax: 154,
    targetRangeMin: 141,
    targetRangeMax: 145,
    stopPrice: 159,
    holdDays: 3,
    confidenceScore: 'balanced',
    actionLabel: '반등 시 매도',
    reasonLine: '단기 반등 이후 거래량이 약해져 3영업일 내 되돌림 가능성이 있습니다.',
  },
];

// Aggressive recommendations
const aggressiveRecommendations: RecommendationCard[] = [
  {
    id: 'nvda-aggressive',
    ticker: 'NVDA',
    companyName: 'Nvidia',
    direction: 'BUY',
    entryRangeMin: 835,
    entryRangeMax: 845,
    targetRangeMin: 900,
    targetRangeMax: 925,
    stopPrice: 805,
    holdDays: 3,
    confidenceScore: 'aggressive',
    actionLabel: '빠른 진입',
    reasonLine: '데이터센터 수요와 최근 거래량 회복이 단기 추세 유지 가능성을 높입니다.',
  },
  {
    id: 'aapl-aggressive',
    ticker: 'AAPL',
    companyName: 'Apple',
    direction: 'BUY',
    entryPrice: 169.80,
    targetPrice: 179.50,
    stopPrice: 164.00,
    holdDays: 3,
    confidenceScore: 'aggressive',
    actionLabel: '공격 매수',
    reasonLine: '신제품 기대보다 자사주 매입과 방어적 수급이 단기 하방을 제한하고 있습니다.',
  },
  {
    id: 'tsla-aggressive',
    ticker: 'TSLA',
    companyName: 'Tesla',
    direction: 'SELL',
    entryRangeMin: 153,
    entryRangeMax: 156,
    targetRangeMin: 137,
    targetRangeMax: 142,
    stopPrice: 161,
    holdDays: 2,
    confidenceScore: 'aggressive',
    actionLabel: '단기 매도',
    reasonLine: '단기 반등 이후 거래량이 약해져 3영업일 내 되돌림 가능성이 있습니다.',
  },
];

// Conservative recommendations
const conservativeRecommendations: RecommendationCard[] = [
  {
    id: 'nvda-conservative',
    ticker: 'NVDA',
    companyName: 'Nvidia',
    direction: 'BUY',
    entryRangeMin: 805,
    entryRangeMax: 818,
    targetRangeMin: 852,
    targetRangeMax: 868,
    stopPrice: 785,
    holdDays: 7,
    confidenceScore: 'conservative',
    actionLabel: '눌림 확인',
    reasonLine: '데이터센터 수요와 최근 거래량 회복이 단기 추세 유지 가능성을 높입니다.',
  },
  {
    id: 'aapl-conservative',
    ticker: 'AAPL',
    companyName: 'Apple',
    direction: 'BUY',
    entryPrice: 166.20,
    targetPrice: 173.20,
    stopPrice: 161.50,
    holdDays: 6,
    confidenceScore: 'conservative',
    actionLabel: '안정 진입',
    reasonLine: '신제품 기대보다 자사주 매입과 방어적 수급이 단기 하방을 제한하고 있습니다.',
  },
  {
    id: 'tsla-conservative',
    ticker: 'TSLA',
    companyName: 'Tesla',
    direction: 'SELL',
    entryRangeMin: 148,
    entryRangeMax: 151,
    targetRangeMin: 143,
    targetRangeMax: 146,
    stopPrice: 156,
    holdDays: 5,
    confidenceScore: 'conservative',
    actionLabel: '보수 관찰',
    reasonLine: '단기 반등 이후 거래량이 약해져 3영업일 내 되돌림 가능성이 있습니다.',
  },
];

export const recommendationsByRisk = {
  conservative: conservativeRecommendations,
  balanced: balancedRecommendations,
  aggressive: aggressiveRecommendations,
};

export const performanceRecords: PerformanceRecord[] = [
  {
    ticker: 'NVDA',
    predictedDirection: 'BUY',
    realizedReturn: '+4.8%',
    hitFlag: 'success',
    evaluationWindowDays: 5,
    evaluatedAt: '2026-04-19',
  },
  {
    ticker: 'AAPL',
    predictedDirection: 'BUY',
    realizedReturn: '+2.1%',
    hitFlag: 'success',
    evaluationWindowDays: 4,
    evaluatedAt: '2026-04-18',
  },
  {
    ticker: 'TSLA',
    predictedDirection: 'SELL',
    realizedReturn: '-3.4%',
    hitFlag: 'success',
    evaluationWindowDays: 3,
    evaluatedAt: '2026-04-17',
  },
  {
    ticker: 'META',
    predictedDirection: 'BUY',
    realizedReturn: '-1.2%',
    hitFlag: 'fail',
    evaluationWindowDays: 5,
    evaluatedAt: '2026-04-16',
  },
  {
    ticker: 'MSFT',
    predictedDirection: 'BUY',
    realizedReturn: '+0.8%',
    hitFlag: 'success',
    evaluationWindowDays: 4,
    evaluatedAt: '2026-04-15',
  },
  {
    ticker: 'AMZN',
    predictedDirection: 'SELL',
    realizedReturn: '+1.6%',
    hitFlag: 'fail',
    evaluationWindowDays: 3,
    evaluatedAt: '2026-04-14',
  },
  {
    ticker: 'NVDA',
    predictedDirection: 'BUY',
    realizedReturn: '+6.2%',
    hitFlag: 'success',
    evaluationWindowDays: 5,
    evaluatedAt: '2026-04-13',
  },
  {
    ticker: 'AAPL',
    predictedDirection: 'SELL',
    realizedReturn: '-2.4%',
    hitFlag: 'success',
    evaluationWindowDays: 4,
    evaluatedAt: '2026-04-12',
  },
  {
    ticker: 'TSLA',
    predictedDirection: 'BUY',
    realizedReturn: '-0.5%',
    hitFlag: 'fail',
    evaluationWindowDays: 3,
    evaluatedAt: '2026-04-11',
  },
  {
    ticker: 'META',
    predictedDirection: 'BUY',
    realizedReturn: '+3.7%',
    hitFlag: 'success',
    evaluationWindowDays: 5,
    evaluatedAt: '2026-04-10',
  },
];
